### ISSUE TITLE
Can't add beoplay media player to HA workspace

### ISSUE THREAD

**Issue by mbolo01** [giachello/beoplay#1]
Bonjour!
I'm currently using the legacy beoplay HA integration and I tried the one you published without success.

What I have done so far:

- Legacy ha-beoplay directory is present in custom_components
- Moved the former beoplay directory out of custom_components
- Commented out previous beoplay entries in configuration.yaml
- Installed the new beoplay directory pulled from your repository into custom_components
- Added beoplay section in configuration.yaml as per the README.CMD: FAILED HA configuration checks
- Added a device via the configuration flow/ Integration add successfully
- I'm not able to find the device when I want to add it my HA Workspace while looking for media_player entity.

Note: I'm not a developer, so apologize my poor skills here
Note 2: I'm a member of the Beoworld forum

Kind regards.
Jérôme

**Comment by giachello** [comment]
Hi sorry, didn't see this message earlier.
the new beoplay can be configured in the UI. Configuration->Integrations->ADD+-> Beoplay
Let me know if it works!

**Comment by mbolo01** [comment]
No worries, thanks for answering.
I tried the UI too as mentioned in my first post. I can add a device via the UI but I'm not able to find it later to add it in my workspace as media-player. I also have several errors messages in the console (using a docker version of HA in a QNAP NAS).
I'll try again and report the error messages, but I'd rather wait for multiple device support as I have several devices to integrate.
Kind regards

**Comment by giachello** [comment]
Do send the error messages when you have a chance, it's the only way to debug the problem :-)

**Comment by mbolo01** [comment]
Ok, here we go.
Steps I did: stopped HA, removed former beoplay code from the custom_components, added yours, commented out any reference in configuration.yaml, started HA, added beoplay integration, added a device by entering its IP address and selecting Speaker.
At the time I added the Beoplay integration and registered the device, the following events appeared in the docker console:
_2021-01-20 18:19:54 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing beoplay/group.py                                                                            
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process                                                                                        
    platform = integration.get_platform(platform_name)                                                                                                                                                     
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform                                                                                                         
    cache[full_name] = self._import_platform(platform_name)                                                                                                                                                
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform                                                                                                     
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")                                                                                                                                     
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                                        
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                                                          
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                        
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked                                                                                                                               
ModuleNotFoundError: No module named 'custom_components.beoplay NEW.group'                                                                                                                                 
2021-01-20 18:19:54 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing beoplay/system_health.py                                                                    
Traceback (most recent call last):                                                                                                                                                                         
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process                                                                                        
    platform = integration.get_platform(platform_name)                                                                                                                                                     
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform                                                                                                         
    cache[full_name] = self._import_platform(platform_name)                                                                                                                                                
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform                                                                                                     
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")                                                                                                                                     
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                                        
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                           
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                                                                       
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked                                                                                                                              
ModuleNotFoundError: No module named 'custom_components.beoplay NEW.system_health'                                                                                                                        
2021-01-20 18:19:54 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing beoplay/logbook.py                                                                         
Traceback (most recent call last):                                                                                                                                                                        
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process                                                                                       
    platform = integration.get_platform(platform_name)                                                                                                                                                    
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform                                                                                                        
    cache[full_name] = self._import_platform(platform_name)                                                                                                                                               
  File "/usr/local/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform                                                                                                    
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")                                                                                                                                    
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                           
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load_                                                                                                                                       

Integration added successfully:
<img width="657" alt="Capture d’écran 2021-01-20 à 19 20 17" src="https://user-images.githubusercontent.com/57586871/105219547-dee81980-5b56-11eb-882e-5556277b9bbf.png">
<img width="446" alt="Capture d’écran 2021-01-20 à 19 20 44" src="https://user-images.githubusercontent.com/57586871/105219606-f0c9bc80-5b56-11eb-8de5-5adab5eb736b.png">

Could not find any "beoplay" integration:
<img width="1078" alt="Capture d’écran 2021-01-20 à 19 27 37" src="https://user-images.githubusercontent.com/57586871/105219673-04752300-5b57-11eb-8bf9-4d40afdaacb7.png">

Kind regards

**Comment by mbolo01** [comment]
EDIT: I fixed the console error messages by naming the beoplay directory in custom_components "beoplay" v.s. other names I used to remember which version I was using.
Then I added two integrations for two different Beoplay devices that I named differently and I'm still unable to find then in entities or devices.

**Comment by mbolo01** [comment]
After some cleanup, I managed to identify the entities created by your code.
Next steps: bring back album cover and other info to the media_player card.

**Comment by giachello** [comment]
Great to hear!
