### ISSUE TITLE
events stops working

### ISSUE THREAD

**Issue by KimCarlsen** [giachello/beoplay#23]
Hi. 
after upgrade to v2022.10.2, the event listerner suddenly stops working.
In log i get this:
This error originated from a custom integration.

Logger: custom_components.beoplay.media_player
Source: helpers/entity.py:529
Integration: Bang & Olufsen BeoPlay Devices
First occurred: 18:58:18 (2 occurrences)
Last logged: 19:06:34

Unexpected error in
Traceback (most recent call last):
  File "/config/custom_components/beoplay/media_player.py", line 275, in _start_poll_command
    await self.async_update_status()
  File "/config/custom_components/beoplay/media_player.py", line 336, in async_update_status
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 678, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 529, in async_write_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity

**Comment by giachello** [comment]
I am rewriting how that part works. Should have some updates later this week.

**Comment by giachello** [comment]
So this should be fixed now. Please check out v2023.1.1
