### ISSUE TITLE
`async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by mbolo01** [giachello/beoplay#38]
Hi there - In case you have not seen this message from HA Console:

2024-04-06 17:16:01.310 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'beoplay' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/beoplay/media_player.py, line 278: self._polling_task = self._hass.async_add_job(self._start_poll_command()), please create a bug report at https://github.com/giachello/beoplay/issues

KR,
Jérôme

**Comment by giachello** [comment]
fixed in 2024.4.1

**Comment by mbolo01** [comment]
Merci!

**Comment by mbolo01** [comment]
After updating to 2024.4.1 I have the following errors:

2024-04-07 13:41:29.145 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up beoplay platform for media_player
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/beoplay/media_player.py", line 200, in async_setup_entry
    type = config_entry.data[CONF_TYPE]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'type'
2024-04-07 13:41:29.872 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up beoplay platform for media_player
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/beoplay/media_player.py", line 200, in async_setup_entry
    type = config_entry.data[CONF_TYPE]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'type'
2024-04-07 13:41:30.841 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up beoplay platform for media_player
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/beoplay/media_player.py", line 200, in async_setup_entry
    type = config_entry.data[CONF_TYPE]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'type'

**Comment by giachello** [comment]
Try deleting and re installing the integrtion

**Comment by mbolo01** [comment]
Re-install closes the issue, thanks. Shall I close the issue I raised or do you want to comment/close it for tracking ?
