### ISSUE TITLE
Errors after updating to 2024.4.1

### ISSUE THREAD

**Issue by mbolo01** [giachello/beoplay#39]
2024-04-07 13:41:29.145 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up beoplay platform for media_player
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/beoplay/media_player.py", line 200, in async_setup_entry
type = config_entry.data[CONF_TYPE]
~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'type'

**Comment by exzz** [comment]
Same here :-(

**Comment by mbolo01** [comment]
@exzz : giachello advised me to delete and re install the integration which worked for me.

**Comment by exzz** [comment]
@mbolo01: it works, many thanks for your help.

**Comment by sallstrombeohome** [comment]
> @exzz : giachello advised me to delete and re install the integration which worked for me.

Are the settings still there after you did this, or must you make them again?

**Comment by giachello** [comment]
There is really only just one setting, but yes you need to re-add the integration.
