### ISSUE TITLE
Beovision eclipse error 

### ISSUE THREAD

**Issue by mikkel328a** [giachello/beoplay#43]
I get this error sometimes - It will not update the status- ex. The source 

This error originated from a custom integration.

Logger: custom_components.beoplay.media_player
Source: custom_components/beoplay/media_player.py:262
integration: BeoPlay for Bang & Olufsen (documentation, issues)
First occurred: 23:07:29 (1 occurrences)
Last logged: 23:07:29

Unexpected error in BEOVISION ECLIPSE
Traceback (most recent call last):
  File "/config/custom_components/beoplay/media_player.py", line 262, in _start_poll_command
    await self.async_update_status()
  File "/config/custom_components/beoplay/media_player.py", line 298, in async_update_status
    await self._speaker.async_notificationsTask(notif_callback)
  File "/usr/local/lib/python3.12/site-packages/pybeoplay/__init__.py", line 231, in async_notificationsTask
    self._processNotification(data_json)
  File "/usr/local/lib/python3.12/site-packages/pybeoplay/__init__.py", line 920, in _processNotification
    self._processSoundMode(data)
  File "/usr/local/lib/python3.12/site-packages/pybeoplay/__init__.py", line 905, in _processSoundMode
    self.soundMode = data["notification"]["data"]["friendlyName"]
    ^^^^^^^^^^^^^^
AttributeError: property 'soundMode' of 'BeoPlay' object has no setter

**Comment by dkonopacki** [comment]
I have the same issue with my Stage. When it happens to me, the BeoPlay integration stops publishing events. The only way to get it back is to reload the config.

This CR looks to be the culprit:
https://github.com/giachello/pybeoplay/commit/bcee56795da40573c3673f558d8849ac7e00c72b#diff-f8c6ffbc6f7992cd19046c23244c5d20a793e476912097c466c3b2d36a2afbc3R864

The faulty line looks like it was either meant to call the local variable `_soundModes` or the setter function was forgotten. 

Hopefully this helps with troubleshooting!

**Comment by dkonopacki** [comment]
@mikkel328a - If you find that you are having issues with your automations because of this bug, you can use this has a hack to kick your service back into operation.

Create a Timer Helper. I named mine `time.beoplay_timeout` and set mine to a 5 seconds. This works off the assumption that the state is playing and triggering at a regular interval. Because I am using it for a TV that I am controlling through HA with a BR1, this works for me. I have a second automation that determines whether the TV is active or not, and that toggles the config reload automation on or off.

Tweak as you need to. Just change the entity id that you need reloaded. Hopefully this helps until there’s a fix!

[YAML Gist](https://gist.github.com/dkonopacki/255533bb970719c24a3d8a603ba08636)

**Comment by giachello** [comment]
@hugobloem this is part of the code you added... could you please check?

**Comment by hugobloem** [comment]
Sorry I haven't been home so I was not able to test this. I created a PR to fix this (https://github.com/giachello/pybeoplay/pull/7).
